#!/bin/bash
#/usr/bin/skybian-chrootconfig
#this script is run with the assumption
#that the skybian package is installed in chroot
#and that this script is being executed in chroot
#as called by the postinstall script of the skybian package
if [[ -f /opt/skywire/skywire.json ]] ; then
  #remove the autogenerated configuration
 rm /opt/skywire/skywire.json
fi
if [[ -f /etc/systemd/system/skywire-boot-config.service ]] ; then
   sudo systemctl enable skywire-boot-config
 fi
if [[ -f /etc/systemd/system/skywire.service ]] ; then
  sudo systemctl disable skywire
fi
if [[ -f /etc/systemd/system/skybian-firstrun.service ]] ; then
  sudo systemctl enable skybian-firstrun
fi
