#!/bin/bash

#https://aur.archlinux.org/cgit/aur.git/tree/aur-remote.sh?h=readonly-cache
set -e
if [[ $EUID -ne 0 ]]; then
   echo "You must be root to do this." 1>&2
   exit 100
fi
#the idea is to have the hypervisor's IP in /etc/profile DEBLOCAL=192.168.0.2
if [ -z $DEBLOCAL ]; then
  set -ex
#prompt to enter sky manager IP address
read -p "Please input IP address of the Hypervisor: " -r
DEBLOCAL=${REPLY}
fi

# backup /etc/apt/sources.list
[ ! -f /etc/apt/sources.list.bak ] && cp /etc/apt/sources.list /etc/apt/sources.list.bak

#set the DEBLOCAL IP as a mirror for apt to retrieve updates from
[[ $(cat /etc/apt/sources.list | grep "http://$DEBLOCAL:8079") = *"http://$DEBLOCAL:8079"* ]] && add-apt-repository "deb [trusted=yes] http://$DEBLOCAL:8079 sid main"
